schema-version = 1
release-version = "1.38.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.61.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "2.3.3"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "8.0.0"
vendor = "bottlerocket"
