schema-version = 1
release-version = "1.36.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.60.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "2.1.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "6.3.0"
vendor = "bottlerocket"
