schema-version = 1
release-version = "1.45.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.63.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "4.0.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "10.1.2"
vendor = "bottlerocket"
