schema-version = 1
release-version = "1.43.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.63.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "3.3.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "9.2.1"
vendor = "bottlerocket"
