schema-version = 1
release-version = "1.35.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.60.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "1.3.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "6.1.1"
vendor = "bottlerocket"
