schema-version = 2
release-version = "1.45.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.64.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "4.2.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "10.3.0"
vendor = "bottlerocket"
