[settings.kubernetes.credential-providers.ecr-credential-provider]
enabled = true
cache-duration = "12h"
image-patterns = [
    "*.dkr.ecr.*.amazonaws.com",
    "*.dkr.ecr.*.amazonaws.com.cn",
    "*.dkr.ecr-fips.*.amazonaws.com",
    "*.dkr.ecr.eu-isoe-west-1.cloud.adc-e.uk",
    "*.dkr.ecr-fips.eu-isoe-west-1.cloud.adc-e.uk",
    "*.dkr.ecr.us-iso-east-1.c2s.ic.gov",
    "*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov"
]
