[package]
name = "docs"
version = "1.0.0"
edition = "2024"
authors = [ "DrMundo0 <noreply@github.com>" ]

[dependencies]
clap = "2"
regex = "1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
