name: Rust-build-docs

on:
  push:
    branches: [ "1.18.x" ]
  pull_request:
    branches: [ "1.18.x" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --manifest-path=docs/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=docs/Cargo.toml --verbose
